name: API & UI Automation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Run Postman Tests (Newman)
      run: npx newman run postman/ecommerce_tests.postman_collection.json -e postman/ecommerce_dev.postman_environment.json

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright Tests
      run: npx playwright test

    # --- KROK 2: TESTY WYDAJNOŚCIOWE (k6) ---
    - name: Run k6 Load Test
      uses: grafana/k6-action@v0.3.1
      with:
        filename: k6/load_test.js